#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from options1.ui on Fri Mar 15 23:32:36 2019
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Page(object):
    def setupUi(self, Page):
        Page.setObjectName(_fromUtf8("Page"))
        Page.resize(502, 673)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Page)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.playlistGroup = QtGui.QGroupBox(Page)
        self.playlistGroup.setObjectName(_fromUtf8("playlistGroup"))
        self.vboxlayout = QtGui.QVBoxLayout(self.playlistGroup)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.kcfg_TagsFromRegex = QtGui.QCheckBox(self.playlistGroup)
        self.kcfg_TagsFromRegex.setObjectName(_fromUtf8("kcfg_TagsFromRegex"))
        self.vboxlayout.addWidget(self.kcfg_TagsFromRegex)
        self.regexInfoGroup = QtGui.QGroupBox(self.playlistGroup)
        self.regexInfoGroup.setTitle(_fromUtf8(""))
        self.regexInfoGroup.setFlat(True)
        self.regexInfoGroup.setObjectName(_fromUtf8("regexInfoGroup"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.regexInfoGroup)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.kcfg_TagRegex = QtGui.QLineEdit(self.regexInfoGroup)
        self.kcfg_TagRegex.setObjectName(_fromUtf8("kcfg_TagRegex"))
        self.vboxlayout1.addWidget(self.kcfg_TagRegex)
        self.kcfg_TagRegexMode = KButtonGroup(self.regexInfoGroup)
        self.kcfg_TagRegexMode.setFlat(True)
        self.kcfg_TagRegexMode.setObjectName(_fromUtf8("kcfg_TagRegexMode"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.kcfg_TagRegexMode)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.radio1 = QtGui.QRadioButton(self.kcfg_TagRegexMode)
        self.radio1.setObjectName(_fromUtf8("radio1"))
        self.vboxlayout2.addWidget(self.radio1)
        self.radio2 = QtGui.QRadioButton(self.kcfg_TagRegexMode)
        self.radio2.setObjectName(_fromUtf8("radio2"))
        self.vboxlayout2.addWidget(self.radio2)
        self.radio3 = QtGui.QRadioButton(self.kcfg_TagRegexMode)
        self.radio3.setObjectName(_fromUtf8("radio3"))
        self.vboxlayout2.addWidget(self.radio3)
        self.vboxlayout1.addWidget(self.kcfg_TagRegexMode)
        self.vboxlayout.addWidget(self.regexInfoGroup)
        self.verticalLayout_3.addWidget(self.playlistGroup)
        self.lastfmGroup = QtGui.QGroupBox(Page)
        self.lastfmGroup.setObjectName(_fromUtf8("lastfmGroup"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.lastfmGroup)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.kcfg_EnableLastfm = QtGui.QCheckBox(self.lastfmGroup)
        self.kcfg_EnableLastfm.setObjectName(_fromUtf8("kcfg_EnableLastfm"))
        self.verticalLayout_2.addWidget(self.kcfg_EnableLastfm)
        self.lastfmFrame = QtGui.QFrame(self.lastfmGroup)
        self.lastfmFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.lastfmFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.lastfmFrame.setObjectName(_fromUtf8("lastfmFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.lastfmFrame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.lastfmFrame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.kcfg_LastfmUser = QtGui.QLineEdit(self.lastfmFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kcfg_LastfmUser.sizePolicy().hasHeightForWidth())
        self.kcfg_LastfmUser.setSizePolicy(sizePolicy)
        self.kcfg_LastfmUser.setObjectName(_fromUtf8("kcfg_LastfmUser"))
        self.gridLayout.addWidget(self.kcfg_LastfmUser, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.lastfmFrame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.kcfg_LastfmPassword = QtGui.QLineEdit(self.lastfmFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kcfg_LastfmPassword.sizePolicy().hasHeightForWidth())
        self.kcfg_LastfmPassword.setSizePolicy(sizePolicy)
        self.kcfg_LastfmPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.kcfg_LastfmPassword.setObjectName(_fromUtf8("kcfg_LastfmPassword"))
        self.gridLayout.addWidget(self.kcfg_LastfmPassword, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.lastfmFrame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.kcfg_LastfmServer = QtGui.QComboBox(self.lastfmFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kcfg_LastfmServer.sizePolicy().hasHeightForWidth())
        self.kcfg_LastfmServer.setSizePolicy(sizePolicy)
        self.kcfg_LastfmServer.setObjectName(_fromUtf8("kcfg_LastfmServer"))
        self.gridLayout.addWidget(self.kcfg_LastfmServer, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        self.kcfg_LastfmURL = QtGui.QLineEdit(self.lastfmFrame)
        self.kcfg_LastfmURL.setToolTip(_fromUtf8(""))
        self.kcfg_LastfmURL.setObjectName(_fromUtf8("kcfg_LastfmURL"))
        self.gridLayout.addWidget(self.kcfg_LastfmURL, 3, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.lastfmFrame)
        self.kcfg_EnableLastfm.raise_()
        self.lastfmFrame.raise_()
        self.verticalLayout_3.addWidget(self.lastfmGroup)
        spacerItem4 = QtGui.QSpacerItem(17, 198, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)

        self.retranslateUi(Page)
        QtCore.QMetaObject.connectSlotsByName(Page)

    def retranslateUi(self, Page):
        Page.setWindowTitle(kdecore.i18n(_fromUtf8("Configuring Minirok")))
        self.playlistGroup.setTitle(kdecore.i18n(_fromUtf8("Playlist")))
        self.kcfg_TagsFromRegex.setText(kdecore.i18n(_fromUtf8("Use a &regular expression to guess tags from the filename")))
        self.radio1.setText(kdecore.i18n(_fromUtf8("Use this regex to populate the playlist initially,\n"
"but still read the tags in the background")))
        self.radio2.setText(kdecore.i18n(_fromUtf8("Do not read tags if the regex matches")))
        self.radio3.setText(kdecore.i18n(_fromUtf8("Never read tags from files")))
        self.lastfmGroup.setTitle(kdecore.i18n(_fromUtf8("Last.fm")))
        self.kcfg_EnableLastfm.setText(kdecore.i18n(_fromUtf8("Submit played tracks to &Last.fm")))
        self.label.setText(kdecore.i18n(_fromUtf8("User")))
        self.label_2.setText(kdecore.i18n(_fromUtf8("Password")))
        self.label_3.setText(kdecore.i18n(_fromUtf8("Server")))

from PyKDE4.kdeui import KButtonGroup
